/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProvaRouteImport } from './routes/_authenticated/prova'
import { Route as AuthenticatedTopicoIdRouteImport } from './routes/_authenticated/topico.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvaRoute = AuthenticatedProvaRouteImport.update({
  id: '/prova',
  path: '/prova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTopicoIdRoute = AuthenticatedTopicoIdRouteImport.update({
  id: '/topico/$id',
  path: '/topico/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/prova': typeof AuthenticatedProvaRoute
  '/topico/$id': typeof AuthenticatedTopicoIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/prova': typeof AuthenticatedProvaRoute
  '/': typeof AuthenticatedIndexRoute
  '/topico/$id': typeof AuthenticatedTopicoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/prova': typeof AuthenticatedProvaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/topico/$id': typeof AuthenticatedTopicoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/prova' | '/topico/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/prova' | '/' | '/topico/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/prova'
    | '/_authenticated/'
    | '/_authenticated/topico/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prova': {
      id: '/_authenticated/prova'
      path: '/prova'
      fullPath: '/prova'
      preLoaderRoute: typeof AuthenticatedProvaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/topico/$id': {
      id: '/_authenticated/topico/$id'
      path: '/topico/$id'
      fullPath: '/topico/$id'
      preLoaderRoute: typeof AuthenticatedTopicoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProvaRoute: typeof AuthenticatedProvaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTopicoIdRoute: typeof AuthenticatedTopicoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProvaRoute: AuthenticatedProvaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTopicoIdRoute: AuthenticatedTopicoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
